-- Schema inicial — Sistema de Chamados (Comunicação Interna)
-- Dialeto: Oracle 12c+ (usa GENERATED BY DEFAULT AS IDENTITY).
-- Se a versão do Oracle da empresa for anterior a 12c, trocar cada IDENTITY por
-- uma SEQUENCE + TRIGGER "BEFORE INSERT" equivalente (documentado no README).

CREATE TABLE tipo_solicitacao (
  id                     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome                   VARCHAR2(120) NOT NULL UNIQUE,
  sla_dias               NUMBER(4) NOT NULL,
  sla_conta_dias_uteis   CHAR(1) DEFAULT 'S' NOT NULL CHECK (sla_conta_dias_uteis IN ('S','N')),
  requer_briefing_evento CHAR(1) DEFAULT 'N' NOT NULL CHECK (requer_briefing_evento IN ('S','N')),
  ativo                  CHAR(1) DEFAULT 'S' NOT NULL CHECK (ativo IN ('S','N')),
  ordem_exibicao         NUMBER DEFAULT 0 NOT NULL,
  criado_em              TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  atualizado_em          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE area_solicitante (
  id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome           VARCHAR2(150) NOT NULL UNIQUE,
  ativo          CHAR(1) DEFAULT 'S' NOT NULL CHECK (ativo IN ('S','N')),
  ordem_exibicao NUMBER DEFAULT 0 NOT NULL
);

CREATE TABLE analista (
  id               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome             VARCHAR2(200) NOT NULL,
  email            VARCHAR2(200) NOT NULL UNIQUE,
  keycloak_subject VARCHAR2(255),
  papel            VARCHAR2(20) DEFAULT 'analista' NOT NULL CHECK (papel IN ('analista','coordenador')),
  cor              VARCHAR2(7) DEFAULT '#3b6fd4' NOT NULL,
  ativo            CHAR(1) DEFAULT 'S' NOT NULL CHECK (ativo IN ('S','N')),
  criado_em        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE regra_roteamento (
  id                     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  area_id                NUMBER REFERENCES area_solicitante(id),
  tipo_solicitacao_id    NUMBER REFERENCES tipo_solicitacao(id),
  analista_principal_id  NUMBER NOT NULL REFERENCES analista(id),
  analista_secundario_id NUMBER REFERENCES analista(id),
  responsavel_sla        VARCHAR2(20) DEFAULT 'PRINCIPAL' NOT NULL CHECK (responsavel_sla IN ('PRINCIPAL','SECUNDARIO')),
  prioridade             NUMBER DEFAULT 0 NOT NULL,
  ativo                  CHAR(1) DEFAULT 'S' NOT NULL CHECK (ativo IN ('S','N')),
  observacao             VARCHAR2(400),
  atualizado_por         VARCHAR2(200),
  atualizado_em          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE regra_roteamento_publico (
  regra_id NUMBER NOT NULL REFERENCES regra_roteamento(id) ON DELETE CASCADE,
  publico  VARCHAR2(30) NOT NULL CHECK (publico IN ('Holding','Operacao-Lojas','Operacao-CD','Todos')),
  PRIMARY KEY (regra_id, publico)
);

CREATE TABLE contador_protocolo (
  ano           NUMBER(4) PRIMARY KEY,
  ultimo_numero NUMBER DEFAULT 0 NOT NULL
);

CREATE TABLE chamado (
  id                        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  protocolo                 VARCHAR2(20) NOT NULL UNIQUE,
  publico                   VARCHAR2(30) NOT NULL CHECK (publico IN ('Holding','Operacao-Lojas','Operacao-CD','Todos')),
  area_id                   NUMBER REFERENCES area_solicitante(id),
  tipo_solicitacao_id       NUMBER NOT NULL REFERENCES tipo_solicitacao(id),
  solicitante_nome          VARCHAR2(200),
  solicitante_email         VARCHAR2(200),
  solicitante_local_texto   VARCHAR2(300),
  publico_alvo_conteudo     VARCHAR2(30) CHECK (publico_alvo_conteudo IN ('Escritorio_SP','Lojas','CD')),
  descricao                 CLOB,
  conteudo_pronto_ref       CHAR(1) DEFAULT 'N' NOT NULL CHECK (conteudo_pronto_ref IN ('S','N')),
  conteudo_pronto_ref_texto VARCHAR2(2000),
  analista_principal_id     NUMBER REFERENCES analista(id),
  analista_secundario_id    NUMBER REFERENCES analista(id),
  status                    VARCHAR2(30) DEFAULT 'aguardando_aprovacao' NOT NULL
                             CHECK (status IN ('aguardando_aprovacao','novo','em_andamento','em_revisao',
                                                'aguardando_solicitante','resolvido','cancelado')),
  data_abertura             TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  data_inicio_sla           TIMESTAMP,
  data_prazo                TIMESTAMP,
  data_resolucao            TIMESTAMP,
  sla_dias_snapshot         NUMBER,
  sla_conta_uteis_snapshot  CHAR(1),
  segundo_aprovador_nome    VARCHAR2(200),
  segundo_aprovador_email   VARCHAR2(200),
  aprovacao_status          VARCHAR2(20) DEFAULT 'nao_aplicavel' NOT NULL
                             CHECK (aprovacao_status IN ('nao_aplicavel','pendente','aprovado','rejeitado')),
  ciencia_sla               CHAR(1) DEFAULT 'N' NOT NULL CHECK (ciencia_sla IN ('S','N')),
  contador_revisao_conteudo NUMBER DEFAULT 0 NOT NULL,
  contador_revisao_design   NUMBER DEFAULT 0 NOT NULL,
  chamado_origem_id         NUMBER REFERENCES chamado(id),
  criado_em                 TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  atualizado_em             TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX ix_chamado_status ON chamado(status);
CREATE INDEX ix_chamado_analista_principal ON chamado(analista_principal_id);
CREATE INDEX ix_chamado_prazo ON chamado(data_prazo);

CREATE TABLE chamado_evento_detalhe (
  chamado_id                       NUMBER PRIMARY KEY REFERENCES chamado(id) ON DELETE CASCADE,
  nome_evento                      VARCHAR2(300) NOT NULL,
  responsavel_nome                 VARCHAR2(200) NOT NULL,
  responsavel_area                 VARCHAR2(150),
  responsavel_email                VARCHAR2(200) NOT NULL,
  responsavel_telefone             VARCHAR2(30),
  objetivo                         CLOB,
  publico_evento                   VARCHAR2(300),
  qtd_participantes_estimada       NUMBER,
  data_desejada                    DATE,
  horario_inicio                   VARCHAR2(5),
  horario_fim                      VARCHAR2(5),
  flexibilidade_data               CHAR(1) DEFAULT 'N' NOT NULL CHECK (flexibilidade_data IN ('S','N')),
  local_definido                   CHAR(1) DEFAULT 'N' NOT NULL CHECK (local_definido IN ('S','N')),
  local_texto                      VARCHAR2(500),
  formato                          VARCHAR2(20) CHECK (formato IN ('presencial','online','hibrido')),
  dinamica_evento                  CLOB,
  identidade_visual_status         VARCHAR2(20) CHECK (identidade_visual_status IN ('definida','nao_definida','em_desenvolvimento')),
  budget_status                    VARCHAR2(20) CHECK (budget_status IN ('disponivel','nao_disponivel','em_aprovacao')),
  budget_valor_estimado            NUMBER(14,2),
  fornecedor_parceiro              VARCHAR2(2000),
  restricoes_observacoes           CLOB,
  checklist_estrutura              CLOB CHECK (checklist_estrutura IS JSON),
  checklist_materiais_comunicacao  CLOB CHECK (checklist_materiais_comunicacao IS JSON),
  checklist_escopo_esperado        CLOB CHECK (checklist_escopo_esperado IS JSON)
);

CREATE TABLE anexo (
  id               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  chamado_id       NUMBER NOT NULL REFERENCES chamado(id) ON DELETE CASCADE,
  nome_original    VARCHAR2(400) NOT NULL,
  nome_armazenado  VARCHAR2(400) NOT NULL,
  caminho_relativo VARCHAR2(1000) NOT NULL,
  mime_type        VARCHAR2(150),
  tamanho_bytes    NUMBER NOT NULL,
  checksum_sha256  VARCHAR2(64),
  enviado_por      VARCHAR2(200),
  enviado_em       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);
CREATE INDEX ix_anexo_chamado ON anexo(chamado_id);

-- Usada apenas quando ATTACHMENT_STORAGE=oracle_blob (padrão é filesystem, ver README)
CREATE TABLE anexo_conteudo (
  anexo_id  NUMBER PRIMARY KEY REFERENCES anexo(id) ON DELETE CASCADE,
  conteudo  BLOB NOT NULL
);

CREATE TABLE revisao (
  id                NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  chamado_id        NUMBER NOT NULL REFERENCES chamado(id) ON DELETE CASCADE,
  tipo_revisao      VARCHAR2(20) NOT NULL CHECK (tipo_revisao IN ('conteudo','design')),
  numero_sequencial NUMBER NOT NULL,
  solicitado_por    VARCHAR2(200),
  descricao         CLOB,
  criado_em         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);
CREATE INDEX ix_revisao_chamado ON revisao(chamado_id);

CREATE TABLE notificacao (
  id                 NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  chamado_id         NUMBER REFERENCES chamado(id) ON DELETE CASCADE,
  analista_id        NUMBER REFERENCES analista(id),
  destinatario_email VARCHAR2(200) NOT NULL,
  tipo_evento        VARCHAR2(40) NOT NULL,
  assunto            VARCHAR2(300) NOT NULL,
  corpo              CLOB,
  status_envio       VARCHAR2(20) DEFAULT 'pendente' NOT NULL CHECK (status_envio IN ('pendente','enviado','falha')),
  tentativas         NUMBER DEFAULT 0 NOT NULL,
  erro_mensagem      VARCHAR2(1000),
  criado_em          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  enviado_em         TIMESTAMP
);
CREATE INDEX ix_notificacao_status ON notificacao(status_envio);

CREATE TABLE historico_status (
  id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  chamado_id      NUMBER NOT NULL REFERENCES chamado(id) ON DELETE CASCADE,
  status_anterior VARCHAR2(30),
  status_novo     VARCHAR2(30) NOT NULL,
  alterado_por    VARCHAR2(200),
  observacao      VARCHAR2(500),
  alterado_em     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);
CREATE INDEX ix_historico_chamado ON historico_status(chamado_id);

CREATE TABLE feriado (
  data      DATE PRIMARY KEY,
  descricao VARCHAR2(200)
);
