-- Dashboard de Visitas em Loja (Rafael/Operações) — upload de CSV do "Checklist Fácil"
-- e visualização com filtros. Cada importação SUBSTITUI o dataset anterior do analista
-- (confirmado em reunião: o app sempre exporta a planilha completa, não incremental).

ALTER TABLE analista ADD acesso_dashboard_operacoes CHAR(1) DEFAULT 'N' NOT NULL
  CHECK (acesso_dashboard_operacoes IN ('S','N'));

CREATE TABLE visita_loja_importacao (
  id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  analista_id   NUMBER NOT NULL REFERENCES analista(id),
  nome_arquivo  VARCHAR2(400),
  total_linhas  NUMBER NOT NULL,
  importado_por VARCHAR2(200),
  importado_em  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE visita_loja (
  id                            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  analista_id                   NUMBER NOT NULL REFERENCES analista(id),
  importacao_id                 NUMBER NOT NULL REFERENCES visita_loja_importacao(id) ON DELETE CASCADE,
  loja_nome                     VARCHAR2(200) NOT NULL,
  cl_nome                       VARCHAR2(150),
  data_visita                   DATE,
  resultado_geral_pct           NUMBER(5,2),
  resultado_auditoria_fisica_pct NUMBER(5,2),
  resultado_entrevista_lider_pct NUMBER(5,2),
  resultado_validacao_equipe_pct NUMBER(5,2),
  criado_em                     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);
CREATE INDEX ix_visita_loja_analista ON visita_loja(analista_id);
CREATE INDEX ix_visita_loja_data ON visita_loja(data_visita);
CREATE INDEX ix_visita_loja_cl ON visita_loja(cl_nome);

-- Uma linha por pergunta/indicador do checklist, pra viabilizar ranking de
-- top positivos/ofensores sem precisar saber de antemão o nome de cada coluna do CSV.
CREATE TABLE visita_loja_indicador (
  id                 NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  visita_loja_id     NUMBER NOT NULL REFERENCES visita_loja(id) ON DELETE CASCADE,
  pilar              VARCHAR2(30) DEFAULT 'outro' NOT NULL
                      CHECK (pilar IN ('auditoria_fisica','entrevista_lider','validacao_equipe','outro')),
  indicador          VARCHAR2(300) NOT NULL,
  resposta_texto     VARCHAR2(500),
  resposta_positiva  CHAR(1) CHECK (resposta_positiva IN ('S','N'))
);
CREATE INDEX ix_visita_indicador_visita ON visita_loja_indicador(visita_loja_id);
CREATE INDEX ix_visita_indicador_nome ON visita_loja_indicador(indicador);
